### ISSUE TITLE
Display not working

### ISSUE THREAD

**Issue by pbhound** [sbcshop/UPS-Hat-RPi#4]
I have followed the instructions but I am not able to get the display on the UPS hat to work.

any Ideas?

**Comment by sbcshop1** [comment]
@pbhound 
First, you need to check individually whether OLED is working or not, for this switch off the UPS HAT, and stack it to a raspberry pi. And In this repository, we upload a folder, name "Test_oled", inside this folder, there is a file name "main.py", kindly run this file, this file run the OLED screen. OLED Screen is working or not Kindly update

**Comment by whab** [comment]
I'm also encountering an issue with the OLED which displays on occasion a static noise pattern as shown on the attached screenshot below:
![Corrupted display - small](https://user-images.githubusercontent.com/1873093/173027724-4d12e64c-bc94-47ec-90f5-ceed21f17124.jpg)
This did not occur at first, but after adding the following line to /etc/rc.local and restarting the Pi:

    sudo python3 /home/pi/Desktop/UPS_Hat/INA219_UPS.py &

The only way I found to recover the display functionality is to power off the Pi, remove the batteries from the UPS Hat, and power the Pi 4 through USB-C. Then the Test_oled/main.py example works just fine. However, even after re-installing the batteries on the UPS hat and restarting with the UPS Hat as the only source of power, the display still shows the static noise pattern... From there, to get the display to run on UPS Hat power again was to reconnect the main power through USB-C (with the UPS Hat also turned on), power down, and disconnect the main power. This triggers a restart, but then the display seems to work again. However the same issue re-occurs each time I power the Pi with the UPS Hat...

Also my Pi 4 restarts when unplugging its main power (USB-C) with the UPS Hat attached to it: is it the expected behavior???  The Kickstarter campaign page explicitly says: “An uninterruptible power supply (UPS), also known as a battery backup, provides backup power when your regular power source fails or voltage drops to an unacceptable level.”. So the actual  behaviour on my device does not seem right as I would expect the UPS Hat to take over when the main power source stops...

**Comment by sbcshop1** [comment]
It is caused by a power drop at the Raspberry Pi, which can be caused by abruptly unplugging the type C cable or turning off the power. This is a common occurrence with this device. To avoid this problem, connect the type c power to the raspberry pi first, then turn on the UPS HAT, then disconnect the type c power from the raspberry pi or turn off the raspberry pi external power (at this time raspberry pi restart due to sudden power drop)Then reconnect the type c power to the Raspberry Pi after that ( In this process your raspberry pi needs to restart one time if you use UPS backup), The Raspberry Pi now does not restart if the type c power is turned off or if the external power is turned off.
You need to follow this process when you use UPS HAT. if you use this process, your OLED problem is also resolved(static noise pattern)

**Comment by whab** [comment]
This seems to fix the issue. It would be useful to properly document this... Thanks!

**Comment by GeekyTim** [comment]
This method has worked once or twice, but not reliably.  Can you please provide a proper solution which will reset the i2c bus?

**Comment by GeekyTim** [comment]
I just got it working for a few minutes, monitoring the UPS service I have written which monitors the battery status and powers it down if it gets too low - as well as writing to the screen. While in use - i.e. working, no reboot, it failed with a connection timeout:

Feb 19 17:35:17 InfluxPi python3[970]: Traceback (most recent call last):
Feb 19 17:35:17 InfluxPi python3[970]:   File "/home/geekytim/UPS/ups.py", line 16, in <module>
Feb 19 17:35:17 InfluxPi python3[970]:     attachedups = ups.UPS()
Feb 19 17:35:17 InfluxPi python3[970]:   File "/home/geekytim/UPS/upscode/sbcomponents.py", line 69, in __init__
Feb 19 17:35:17 InfluxPi python3[970]:     self.__oled_display = SSD1306()
Feb 19 17:35:17 InfluxPi python3[970]:   File "/home/geekytim/UPS/upscode/oled_091.py", line 96, in __init__
Feb 19 17:35:17 InfluxPi python3[970]:     self.__InitDisplay()
Feb 19 17:35:17 InfluxPi python3[970]:   File "/home/geekytim/UPS/upscode/oled_091.py", line 126, in __InitDisplay
Feb 19 17:35:17 InfluxPi python3[970]:     self.__WriteCommand(DISPLAY_ON)
Feb 19 17:35:17 InfluxPi python3[970]:   File "/home/geekytim/UPS/upscode/oled_091.py", line 120, in __WriteCommand
Feb 19 17:35:17 InfluxPi python3[970]:     self.i2c_write(register=0x00, data=cmd)
Feb 19 17:35:17 InfluxPi python3[970]:   File "/home/geekytim/UPS/upscode/oled_091.py", line 75, in i2c_write
Feb 19 17:35:17 InfluxPi python3[970]:     self.bus.write_byte_data(self.address, register, data)
Feb 19 17:35:17 InfluxPi python3[970]: TimeoutError: [Errno 110] Connection timed out
Feb 19 17:35:17 InfluxPi systemd[1]: UPS.service: Main process exited, code=exited, status=1/FAILURE

And then, without any interaction, it starts working again.

**Comment by GeekyTim** [comment]
And overnight it stopped. I'm now going to try and run without the display to see if that helps.

**Comment by sbcshop1** [comment]
@GeekyTim Could you please share your code with me so that I can assist you?

**Comment by GeekyTim** [comment]
I have uploaded the code to here: https://github.com/GeekyTim/UPSControl

I left this code running (with the screen code commented out) and the UPS performed as expected. I did get some warnings that the Pi was on battery from time to time, but that was because I have not yet fine tuned the code that informs me whether power is connected yet - I made some estimates on simple testing at the start.

**Comment by GeekyTim** [comment]
Code has now been running for a few days - without the display code. I suspect the issue may be due to the code used to update the display. I'm going to add that back in to confirm results.

**Comment by GeekyTim** [comment]
Weirdly, I _might_ have stumbled on a reason for one of the issues I am experiencing with this UPS - not definitive, but a possibility.  This concerns the i2c timeouts I am experiencing (TimeoutError: [Errno 110] Connection timed out).

I have created a case for the Pi/UPS and SSD (see below). It is quite a tight fit. The lid pulls the sides in against the sides of the UPS and Pi. With the lid off, all is okay. When I put the lid on, I get the i2c timeout issue. I take the lid off, and the i2c comes back to life (slowly) - the timeout (TimeoutError: [Errno 110] Connection timed out) is replaced with an input/output error (OSError: [Errno 5] Input/output error), and then the UPS software starts correctly again (using systemd).

![IMG_20230206_144518](https://user-images.githubusercontent.com/4642882/221359239-90f72839-4b1a-4d40-9b31-dc1419274a18.jpg)

I think I need to re-make the case with more tolerance.

This does not explain the 'speckled' screen issue.
